title: Nathan's blog
description: ""
email: nimbotelho@gmail.com
url: "https://enbot.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

username: Nathan Botelho
user_title: Software Developer
user_description: Software developer, focusing on web front-end, I am a student of information systems with a strong interest in the areas of cyber security, artificial intelligence and data protection.

user_npm: https://www.npmjs.com/~enbot
user_github: https://github.com/enbot
user_codepen:  https://codepen.io/NathanBotelho
user_linkedin: https://www.linkedin.com/in/nathanbotelho/

exclude: ['LICENSE', 'package.json', 'src', 'node_modules']