title: Blog de Nathan Botelho
description: ""
email: nimbotelho@gmail.com
baseurl: ""
url: "https://enbot.github.io"
twitter_username: minimal_twitter
github_username:  minimal_github

# Build settings
markdown: kramdown
permalink: /:title/




username: Nathan Botelho
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer

# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# # permalink: /:categories/:title

exclude: ['package.json', 'src' , 'node_modules']