title: Notelho's blog
description: ""
email: nimbotelho@gmail.com
url: "https://notelho.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate_path: /articles/:num/
paginate: 6

author: Notelho
username: Nathan Botelho
user_title: Software Developer
user_description: Software developer, focusing on web front-end, I am a student of information systems with a strong interest in cyber security, artificial intelligence and data protection.

user_npm: https://www.npmjs.com/~notelho
user_github: https://github.com/notelho
user_codepen:  https://codepen.io/NathanBotelho
user_linkedin: https://www.linkedin.com/in/nathanbotelho/

exclude: ['LICENSE', 'TODO.md', 'package.json', 'src', 'node_modules', 'git.sh']

plugins:
  - jekyll-paginate